(define (pascal row col)
  
   (cond ((or (= col 1 ) (= col row)) 1)
   (else (+ (pascal (- row 1) (- col 1)) 
            (pascal (- row 1) col)
            )
         )
   )
)

(define (pascal-display-row n)
  (define (column-iter i)
     (display (pascal n i)) (display " ")
     (if (= i n)
       (newline)
       (column-iter (+ i 1))))
  (column-iter 1))

(define (pascal-display n)
  (define (pascal-display-iter i)
    (pascal-display-row i)
    (if (= i n)
      (newline)
      (pascal-display-iter (+ i 1))))
  (pascal-display-iter 1))
